### ISSUE TITLE
KeyError when anonymizing a file that was previously redacted

### ISSUE THREAD

**Issue by eisenzopf** [eisenzopf/redactomatic#5]
In cases where the user redacted a file previously and then attempts to run anonymization, the following error may occur:
Traceback (most recent call last):
  File "redactomatic.py", line 119, in <module>
    main()
  File "redactomatic.py", line 85, in main
    if "MONEY" in entities: texts, entity_map = anonymize.money(texts, entity_map, ids, args.modality, anon_map) # chats-yes, voice=yes
  File "/Users/eisen/Documents/Work/github/redactomatic/anonymize.py", line 374, in money
    new_text = re.sub(this_regex,lambda x: callback(x,id), text)
  File "/usr/local/anaconda3/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/eisen/Documents/Work/github/redactomatic/anonymize.py", line 374, in <lambda>
    new_text = re.sub(this_regex,lambda x: callback(x,id), text)
  File "/Users/eisen/Documents/Work/github/redactomatic/anonymize.py", line 369, in callback
    entity_map[i][m_id] = r
KeyError: "'9421457124244713'"

**Comment by eisenzopf** [comment]
Issue addressed in v1.4
